<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Mariela Villarreal" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../../../../img/favicon.ico">
    <title>My First Blog Post!!</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../../../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../../../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../../../../post/">BLOG</a></li>
        
        <li><a href="../../../../../projects/">PROJECTS</a></li>
        
        <li><a href="../../../../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../../../../post/2020/12/10/my-first-blog-post/">My First Blog Post!!</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         December 10, 2020 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div class="figure">
<img src="../../../../../post/2020-12-10-my-first-blog-post_files/snake.jpg" />

</div>
<div id="hello" class="section level2">
<h2>Hello!!</h2>
<p>This is my first official blog post, and I am going to use it to show off a little bit. Throughout this class, I learned how to use R, and I loved it. Towards, the end of class, we learned Python. Although, I personally enjoy R more than Python, we can actually use both of these programs at the same time, which is awesome! In the R chuck below, I'm going to be maniupulating some data from the &quot;movies6&quot; dataset from my <a href="../../../../../project/project2/">second project</a>. First, I have to read the dataset in. Then, I start getting some stats.</p>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>movies &lt;- read.csv(&quot;movies6.csv&quot;)
movies %&gt;% summarize(mean(budget)) #average movie budget</code></pre>
<pre><code>##   mean(budget)
## 1     29367479</code></pre>
<pre class="r"><code>movies %&gt;% summarize(max(length)) #maximum movie length</code></pre>
<pre><code>##   max(length)
## 1         251</code></pre>
<pre class="r"><code>movies %&gt;% summarize(min(rating)) #lowest rated movie</code></pre>
<pre><code>##   min(rating)
## 1         1.7</code></pre>
<pre class="r"><code>library(reticulate)</code></pre>
<p>This code shows that the mean budget for the movies in my dataset is $29,367,479, the longest movie in my dataset is 251 minutes, and the lowest rated movie in my dataset has a 1.7.</p>
<p>Let's do the same thing in Python! By using reticulate (in previous chunk), we can let the R and Python chunks talk to each other and share data. Now I can manipulate a dataset from R with Python code!</p>
<pre class="python"><code>r.movies.budget.mean() #average movie budget</code></pre>
<pre><code>## 29367479.367537312</code></pre>
<pre class="python"><code>r.movies.length.max() #maximum movie length</code></pre>
<pre><code>## 251</code></pre>
<pre class="python"><code>r.movies.rating.min() #lowest rated movie</code></pre>
<pre><code>## 1.7</code></pre>
<p>We get the same results!!</p>
<p>We can even work with strings!</p>
<pre class="r"><code>#creating our strings in R
cool_stuff=&quot;hello, how are you?&quot;
other_stuff=&quot;1a2b3c4d5e6f7g&quot;
library(reticulate)</code></pre>
<p>Now we can work with &quot;cool_stuff&quot; and &quot;other_stuff&quot; in Python. Here, I'm splitting up &quot;cool_stuff&quot; by the spaces and pulling out only the numbers from &quot;other_stuff&quot;.</p>
<pre class="python"><code>print(r.cool_stuff)</code></pre>
<pre><code>## hello, how are you?</code></pre>
<pre class="python"><code>print(r.other_stuff)</code></pre>
<pre><code>## 1a2b3c4d5e6f7g</code></pre>
<pre class="python"><code>import re
re.split(r&quot;\s&quot;,r.cool_stuff) #splitting by spaces </code></pre>
<pre><code>## [&#39;hello,&#39;, &#39;how&#39;, &#39;are&#39;, &#39;you?&#39;]</code></pre>
<pre class="python"><code>re.findall(r&quot;\d&quot;,r.other_stuff) #finding only numbers</code></pre>
<pre><code>## [&#39;1&#39;, &#39;2&#39;, &#39;3&#39;, &#39;4&#39;, &#39;5&#39;, &#39;6&#39;, &#39;7&#39;]</code></pre>
<p>Pretty cool, huh? I think so.</p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../../../../js/docs.min.js"></script>
<script src="../../../../../js/main.js"></script>

<script src="../../../../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
