---
title: Fun (?) Facts About Me
author: Mariela Villarreal
date: '2020-12-10'
slug: fun-facts-about-me
categories: []
tags: []
description: ''
---

#Here are some fun facts about me!

##Who am I?
Height: 5'1"

Hometown: [Laredo, Texas](https://en.wikipedia.org/wiki/Laredo%2C_Texas) 

I was a swimmer in high school. My events were the 500 m freestyle and the 100 m backstroke. 

If I had three wishes, I would wish for the chance to go back in time and see Prince in concert, to have a pet sloth, and have to infinitely more wishes. 

##Favorites:

Favorite Song: "De Do Do Do, De Da Da Da" by The Police

Favorite Book: "Wuthering Heights" by Emily Bronte

Favorite Movie: Clueless 

Favorite Color: Blue

Favorite Animal: Sloth

##Things I Find Interesting:

[Causal Loop Paradoxes](https://en.wikipedia.org/wiki/Causal_loop). The one in the movie Somewhere in Time ruined the whole movie for me. I can't even think about it without getting annoyed. 


True Crime Documentaries. The episode titled "Sympathy for the Devil" of the show "I am a Killer" involved a murder that took place in my hometown (not proud of that, by the way).


The story behind any song ever. Especially Fleetwood Mac- I live for all the Stevie/Lindsey drama!